// Generated by gencpp from file following_person/target_srvResponse.msg
// DO NOT EDIT!


#ifndef FOLLOWING_PERSON_MESSAGE_TARGET_SRVRESPONSE_H
#define FOLLOWING_PERSON_MESSAGE_TARGET_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace following_person
{
template <class ContainerAllocator>
struct target_srvResponse_
{
  typedef target_srvResponse_<ContainerAllocator> Type;

  target_srvResponse_()
    : new_id(0)  {
    }
  target_srvResponse_(const ContainerAllocator& _alloc)
    : new_id(0)  {
  (void)_alloc;
    }



   typedef int64_t _new_id_type;
  _new_id_type new_id;





  typedef boost::shared_ptr< ::following_person::target_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::following_person::target_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct target_srvResponse_

typedef ::following_person::target_srvResponse_<std::allocator<void> > target_srvResponse;

typedef boost::shared_ptr< ::following_person::target_srvResponse > target_srvResponsePtr;
typedef boost::shared_ptr< ::following_person::target_srvResponse const> target_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::following_person::target_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::following_person::target_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::following_person::target_srvResponse_<ContainerAllocator1> & lhs, const ::following_person::target_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.new_id == rhs.new_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::following_person::target_srvResponse_<ContainerAllocator1> & lhs, const ::following_person::target_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace following_person

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::following_person::target_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::following_person::target_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::following_person::target_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::following_person::target_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::following_person::target_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::following_person::target_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::following_person::target_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6fc26df7bf098a3b1da13ac086e7ec27";
  }

  static const char* value(const ::following_person::target_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6fc26df7bf098a3bULL;
  static const uint64_t static_value2 = 0x1da13ac086e7ec27ULL;
};

template<class ContainerAllocator>
struct DataType< ::following_person::target_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "following_person/target_srvResponse";
  }

  static const char* value(const ::following_person::target_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::following_person::target_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 new_id\n"
;
  }

  static const char* value(const ::following_person::target_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::following_person::target_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.new_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct target_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::following_person::target_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::following_person::target_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "new_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.new_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOLLOWING_PERSON_MESSAGE_TARGET_SRVRESPONSE_H
