// Generated by gencpp from file following_person/target_srv.msg
// DO NOT EDIT!


#ifndef FOLLOWING_PERSON_MESSAGE_TARGET_SRV_H
#define FOLLOWING_PERSON_MESSAGE_TARGET_SRV_H

#include <ros/service_traits.h>


#include <following_person/target_srvRequest.h>
#include <following_person/target_srvResponse.h>


namespace following_person
{

struct target_srv
{

typedef target_srvRequest Request;
typedef target_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct target_srv
} // namespace following_person


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::following_person::target_srv > {
  static const char* value()
  {
    return "a98d4a4909f050d0050807f31b37be61";
  }

  static const char* value(const ::following_person::target_srv&) { return value(); }
};

template<>
struct DataType< ::following_person::target_srv > {
  static const char* value()
  {
    return "following_person/target_srv";
  }

  static const char* value(const ::following_person::target_srv&) { return value(); }
};


// service_traits::MD5Sum< ::following_person::target_srvRequest> should match
// service_traits::MD5Sum< ::following_person::target_srv >
template<>
struct MD5Sum< ::following_person::target_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::following_person::target_srv >::value();
  }
  static const char* value(const ::following_person::target_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::following_person::target_srvRequest> should match
// service_traits::DataType< ::following_person::target_srv >
template<>
struct DataType< ::following_person::target_srvRequest>
{
  static const char* value()
  {
    return DataType< ::following_person::target_srv >::value();
  }
  static const char* value(const ::following_person::target_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::following_person::target_srvResponse> should match
// service_traits::MD5Sum< ::following_person::target_srv >
template<>
struct MD5Sum< ::following_person::target_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::following_person::target_srv >::value();
  }
  static const char* value(const ::following_person::target_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::following_person::target_srvResponse> should match
// service_traits::DataType< ::following_person::target_srv >
template<>
struct DataType< ::following_person::target_srvResponse>
{
  static const char* value()
  {
    return DataType< ::following_person::target_srv >::value();
  }
  static const char* value(const ::following_person::target_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOLLOWING_PERSON_MESSAGE_TARGET_SRV_H
